apiVersion: v2
name: danube-core
description: Danube core chart (brokers with embedded Raft consensus + Prometheus)
icon: https://raw.githubusercontent.com/danube-messaging/danube/main/wave.png
type: application
version: 0.3.0
appVersion: "v0.8.0"
